---
output: github_document
---

## Reading responses 

## week 2

Tufte, Edward (1997) The decision to launch the space shuttle Challenger.
In: *Visual and statistical thinking: Displays of evidence for making
decisions.* Cheshire, CT: Graphics Press, 16--31.

**Prompt:** Tufte says, "Regardless of the indirect cultural
causes of the accident, there was a clear proximate cause."
Summarize Tufte's explanation of the proximate cause.  

**Response:** 
The proximate cause is that the engineers did not present their data in a clear enough way to prove the correct conclusion that they had made in that the launch should not occur because of the correlation between o-ring damage and temperature.

**Prompt:** Describe the evidence the author presents to 
support those ideas.

**Response:**  
The author creates a pointed graphic that shows a clear correlation between O-ring damage and temperature.

**Prompt:** What data were used in making the decision to launch? What data 
were not used but should have been used (according to Tufte) in making the
launch decision?

**Response:** 
The test bench data for the rockets, all kinds of different damage and tmeperature data that were unnecessary, as well as all kinds of irrelevant comments were sent and used to make this decision. According to tufte, O-ring damage and temperature were the data that they needed to present to draw this correlation.


**Prompt:** On page 23, Tufte presents a graph that provides visual evidence
that the "launch was completely outside the engineering database accumulated 
in 24 previous flight." Describe the structure of this data set:

- Number of observations 
- Data structure: classify each variable as quantitative (continuous or discrete) and categorical (nominal or ordinal and number of levels). 

**Response:**  
24 observations
rocket launch - nomical categorial
temperature-quantitative continuous
damage index - quantitative continuous


**Prompt:** Summarize the main thesis of the paper.  

**Response:** 
The main thesis of the paper is that there are right ways and wrong ways to present data. If the engineers in the Challenger disaster had presented their data correctly to back up their conclusion, they would have had a much better case to prevent this disaster and as such they are at fault.