---
output: github_document
---

## Reading responses 

## week 4 reading prompts  

Wainer, Howard (2014) Fifteen displays about one thing. In: *Medical
illuminations: Using evidence, visualization, and statistical thinking to
improve healthcare.* UK: Oxford University Press, 32--49.

Definition: "Gram staining" (named after its inventor, the Danish scientist 
Hans Christian Gram) is a method of staining to distinguish one type of 
bacterium from another---it can be used as a faster substitute for culturing. 
Gram staining is a category with two levels: some bacteria are Gram stain 
negative and some are Gram stain positive. Read more about it on the  
[Gram stain Wiki](https://en.wikipedia.org/wiki/Gram_stain).  



**Prompt:** Reviewing the article carefully, come up with a list of variables. 
Classify each as quantitative or categorical, and if categorical, the levels. 

**Response:** 

variable name: Gram Strain

- type: Categorical Nominal
- levels (if categorical): 2   

variable name:  Minimum inhibitory concentration

- type: Quantitative continuous
- levels (if categorical):    

variable name: Antibiotic

- type: Categorical Nominal
- levels (if categorical): 3


variable name: Bacteria

- type: Categorical Nominal
- levels (if categorical): 16


 
**Prompt:** The article title is "Fifteen displays about one thing." After 
reading the entire article, what is the "one thing?" Note that the "one thing" 
might imply multiple goals or more than one question. 

**Response:** 
The minimum inhibitory concentration of three antibiotics against positive and negative gram straining bacteria. In other words, which antibiotic should be used to treat a given bacteria.



**Prompt:** In your opinion, which of the 15 displays best answers the 
question(s) about the "one thing?"

**Response:**  
I really like entry 7 - dots. 



**Prompt:** Explain why.  

**Response:** 
You can look at a given bacteria and easil see which of the antibiotics would be effective. The gram-positive and gram negative case is shown, but it doesn't dominate the graph in such a way that it is hard to see effectiveness. I can easily look at this graph and say, " Oh, for gram-positive use Penicilin" or "for gram negative use Neomycin."




**Prompt:** Re-read Wainer's conclusion section. What main points does he make 
about graph design or visual rhetoric that you could apply to your own work 
this term. 

**Response:** 
The best displays present a coherent, memorable picture of the data. The display must be able to answer a question being asked, so having the question in mind that you want to answer with a graph is very important. 

This means that when trying to develop and improve my graphics over time, I have to always keep this question in mind. Also, Wainer states how graphics can always be improved.


